// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lacov_kmat
arma::mat lacov_kmat(const arma::mat& x, arma::sp_mat k);
RcppExport SEXP _SpaceTimeBSS_lacov_kmat(SEXP xSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(lacov_kmat(x, k));
    return rcpp_result_gen;
END_RCPP
}
// lacov_ball
arma::mat lacov_ball(const arma::mat& coords, const arma::vec& time, const arma::mat& x, const double& h, const double& tau);
RcppExport SEXP _SpaceTimeBSS_lacov_ball(SEXP coordsSEXP, SEXP timeSEXP, SEXP xSEXP, SEXP hSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double& >::type h(hSEXP);
    Rcpp::traits::input_parameter< const double& >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(lacov_ball(coords, time, x, h, tau));
    return rcpp_result_gen;
END_RCPP
}
// lacov_ring
arma::mat lacov_ring(const arma::mat& coords, const arma::vec& time, const arma::mat& x, const double& h1, const double& h2, const double& tau);
RcppExport SEXP _SpaceTimeBSS_lacov_ring(SEXP coordsSEXP, SEXP timeSEXP, SEXP xSEXP, SEXP h1SEXP, SEXP h2SEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double& >::type h1(h1SEXP);
    Rcpp::traits::input_parameter< const double& >::type h2(h2SEXP);
    Rcpp::traits::input_parameter< const double& >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(lacov_ring(coords, time, x, h1, h2, tau));
    return rcpp_result_gen;
END_RCPP
}
// lacov_gauss
arma::mat lacov_gauss(const arma::mat& coords, const arma::vec& time, const arma::mat& x, const double& h, const double& tau);
RcppExport SEXP _SpaceTimeBSS_lacov_gauss(SEXP coordsSEXP, SEXP timeSEXP, SEXP xSEXP, SEXP hSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double& >::type h(hSEXP);
    Rcpp::traits::input_parameter< const double& >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(lacov_gauss(coords, time, x, h, tau));
    return rcpp_result_gen;
END_RCPP
}
// stkmat_ring
arma::sp_mat stkmat_ring(const arma::mat& coords, const arma::vec& time, const double& h1, const double& h2, const double& tau);
RcppExport SEXP _SpaceTimeBSS_stkmat_ring(SEXP coordsSEXP, SEXP timeSEXP, SEXP h1SEXP, SEXP h2SEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const double& >::type h1(h1SEXP);
    Rcpp::traits::input_parameter< const double& >::type h2(h2SEXP);
    Rcpp::traits::input_parameter< const double& >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(stkmat_ring(coords, time, h1, h2, tau));
    return rcpp_result_gen;
END_RCPP
}
// stkmat_ball
arma::sp_mat stkmat_ball(const arma::mat& coords, const arma::vec& time, const double& h, const double& tau);
RcppExport SEXP _SpaceTimeBSS_stkmat_ball(SEXP coordsSEXP, SEXP timeSEXP, SEXP hSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const double& >::type h(hSEXP);
    Rcpp::traits::input_parameter< const double& >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(stkmat_ball(coords, time, h, tau));
    return rcpp_result_gen;
END_RCPP
}
// stkmat_gauss
arma::sp_mat stkmat_gauss(const arma::mat& coords, const arma::vec& time, const double& h, const double& tau);
RcppExport SEXP _SpaceTimeBSS_stkmat_gauss(SEXP coordsSEXP, SEXP timeSEXP, SEXP hSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const double& >::type h(hSEXP);
    Rcpp::traits::input_parameter< const double& >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(stkmat_gauss(coords, time, h, tau));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SpaceTimeBSS_lacov_kmat", (DL_FUNC) &_SpaceTimeBSS_lacov_kmat, 2},
    {"_SpaceTimeBSS_lacov_ball", (DL_FUNC) &_SpaceTimeBSS_lacov_ball, 5},
    {"_SpaceTimeBSS_lacov_ring", (DL_FUNC) &_SpaceTimeBSS_lacov_ring, 6},
    {"_SpaceTimeBSS_lacov_gauss", (DL_FUNC) &_SpaceTimeBSS_lacov_gauss, 5},
    {"_SpaceTimeBSS_stkmat_ring", (DL_FUNC) &_SpaceTimeBSS_stkmat_ring, 5},
    {"_SpaceTimeBSS_stkmat_ball", (DL_FUNC) &_SpaceTimeBSS_stkmat_ball, 4},
    {"_SpaceTimeBSS_stkmat_gauss", (DL_FUNC) &_SpaceTimeBSS_stkmat_gauss, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SpaceTimeBSS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
