# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lacov_kmat <- function(x, k) {
    .Call(`_SpaceTimeBSS_lacov_kmat`, x, k)
}

lacov_ball <- function(coords, time, x, h, tau) {
    .Call(`_SpaceTimeBSS_lacov_ball`, coords, time, x, h, tau)
}

lacov_ring <- function(coords, time, x, h1, h2, tau) {
    .Call(`_SpaceTimeBSS_lacov_ring`, coords, time, x, h1, h2, tau)
}

lacov_gauss <- function(coords, time, x, h, tau) {
    .Call(`_SpaceTimeBSS_lacov_gauss`, coords, time, x, h, tau)
}

stkmat_ring <- function(coords, time, h1, h2, tau) {
    .Call(`_SpaceTimeBSS_stkmat_ring`, coords, time, h1, h2, tau)
}

stkmat_ball <- function(coords, time, h, tau) {
    .Call(`_SpaceTimeBSS_stkmat_ball`, coords, time, h, tau)
}

stkmat_gauss <- function(coords, time, h, tau) {
    .Call(`_SpaceTimeBSS_stkmat_gauss`, coords, time, h, tau)
}

